print("grafic academy")
print("grafic\n academy")
phase = "SAKLAM SAKIB"
print(phase)
print(phase + "is coll")
print(phase.upper())
print(phase.lower())
print(phase.upper().isupper())
print(phase.lower().islower())
print(phase.lower().isupper())
print(len(phase))
print(phase[3])
print(phase.index("B"))
print(phase.index("KIB"))
print(phase.replace("sakib"))
